### ISSUE TITLE
Icon request: Whatsapp

### ISSUE THREAD

**Issue by GuruDevOp7884** [feathericons/feather#1148] opened 2022-05-11 15:08 UTC
## Icon Request

* Icon name: Icon request : WhatsApp
* Use case:
* Screenshots of similar icons:
![WHATSICON](https://user-images.githubusercontent.com/88688861/167883911-cede8a73-9d3c-4515-92f6-200e000eb384.png)

**Comment by totoprayogo1916** [comment] 2022-05-14 12:25
Duplicate of #122

**Closed** 2022-10-16 17:50 UTC
