### ISSUE TITLE
Icon Request: vk

### ISSUE THREAD

**Issue by kristall000** [feathericons/feather#454] opened 2018-07-07 18:17 UTC
Icon name: vk
Use case: Link/Button
Example: [fontawesome.com](https://fontawesome.com/icons/vk?style=brands) or [PSD](https://vk.com/doc75344642_449888252) & [EPS](https://vk.com/doc75344642_449888239)
![vk_logo](https://user-images.githubusercontent.com/13225484/42413527-1b4d52d0-822b-11e8-8e1c-b0f335bf1bb0.png)

**Comment by ahtohbi4** [comment] 2019-08-14 08:43
Duplicate of #14

**Comment by colebemis** [comment] 2019-08-16 01:45
Closing this because it's a duplicate of #14

**Closed by colebemis** 2019-08-16 01:45 UTC
Labels: icon request

**Comment by warshell** [comment] 2021-02-20 10:22
any news on this icon request? thanks

**Comment by locness3** [comment] 2021-02-20 11:18
#763 : brand icons are deprecated
