### ISSUE TITLE
Icon request: Brush

### ISSUE THREAD

**Issue by mittalyashu** [feathericons/feather#476] opened 2018-09-17 08:52 UTC
## Icon Request

* Icon name: Brush
* Use case: It can define design.
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/29014463/45613800-0dd0bb00-ba85-11e8-8312-18ba24f25b9a.png)

**Comment by lazarljubenovic** [comment] 2018-09-18 16:00
Duplicate of https://github.com/feathericons/feather/issues/386

**Closed** 2018-09-21 19:36 UTC
Labels: duplicate, icon request
