### ISSUE TITLE
Icon Request: dev-to

### ISSUE THREAD

**Issue by IsAmrish** [feathericons/feather#775] opened 2019-11-02 18:24 UTC
## Icon Request

* Icon name: dev-to
* Use case: It will be useful for linking developer profile on https://dev.to
* Screenshots of similar icons:
https://dev.to/

**Comment by johnletey** [comment] 2019-11-04 20:52
@IsAmrish This is a duplicate of #747.

If your curious as to why it was closed, see #763.

**Comment by colebemis** [comment] 2019-11-05 01:23
Thanks for opening this issue! But I’m gonna go ahead and close this because of #763

**Closed** 2019-11-05 01:24 UTC
